### ISSUE TITLE
INDArray should allow coordinates to be longs

### ISSUE THREAD

**Issue by andrewclegg** [deeplearning4j/nd4j#1026]
At the moment (0.4 rc3.9) you can only address matrix cells by ints meaning the length of each axis is limited to Integer.MAX_VALUE, even though the backends can support long coordinates.

**Comment by saudet** [comment]
Not really a bug, we would need to make custom builds for OpenBLAS, figure out how to use the right binaries for MKL, and wait until cuBLAS (and cuDNN) support 64-bit coordinates as well. Besides it would slow things down on GPU because registers are 32-bit, so we would need to support 2 sets of binaries probably. And it would break the current API of ND4J, or we could come up with something more or less ugly. So it's really an enhancement on hold, IMO.

**Comment by andrewclegg** [comment]
Possibly #1107 is a dupe of this, I wasn't sure if it was the same underlying problem or not.

**Comment by raver119** [comment]
Fixed
