### ISSUE TITLE
Nd4j.writeTxt/readTxt issue

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#1033]
```java
    @Test
    public void testReadWriteTxt() throws Exception {
        INDArray arr = Nd4j.linspace(1,100,100);

        String tempDir = System.getProperty("java.io.tmpdir");
        File writeTo = new File(FilenameUtils.concat(tempDir,UUID.randomUUID().toString() + ".txt"));

        Nd4j.writeTxt(arr, writeTo.getAbsolutePath(), ",");
        INDArray load = Nd4j.readTxt(writeTo.getAbsolutePath());

        assertEquals(arr, load);
        writeTo.delete();
    }
```

EDIT: looks like some issues have been fixed (wasn't up to date). Now I'm getting the following from the test:

java.lang.ArrayIndexOutOfBoundsException: 1
	at org.nd4j.linalg.factory.Nd4j.readTxt(Nd4j.java:1947)

**Comment by eraly** [comment]
Hi Alex. The method call with the separator calls the old code not what I wrote.

https://github.com/deeplearning4j/nd4j/blob/ca5f39656dd2905037b63f755f0fc06a0041b619/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/factory/Nd4j.java#L1696

I left the old code in because we don't have support for the separator yet which is notes here in this issue you filed.
https://github.com/deeplearning4j/nd4j/issues/930

We should support for the separator which is why I left the method in. 
Just calling the right method (without the separator) makes the test above pass. I understand it's a little confusing to have two methods here. I am going to add support for the separator and close out the other issue above and there will no longer be any confusion.
