### ISSUE TITLE
BalanceMinibatches returning empty mini batches

### ISSUE THREAD

**Issue by AkshitaT** [deeplearning4j/nd4j#1146]
I used the code from the master. I notice that you have added an if condition to merge data only when the miniBatch is not empty. The problem is; why, in the first place, is it giving empty minibatches?

On debugging, I notice, it is skipping  the highlighted while loop in the BalanceMinibatches: https://github.com/deeplearning4j/nd4j/blob/dcfbd98c72f82eb5258ce630b1f7f61393f16361/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/dataset/BalanceMinibatches.java#L55

Reproducible repo: https://github.com/AkshitaT/Balanced-Mini-Batches

**Comment by huitseeker** [comment]
Thanks for your detailed report! These empty batches were a consequence of #1625, and this behavior is in this case intended. This is now fixed, since I've tested the issue on your project, slightly adapted to fit the modern code base:
https://github.com/huitseeker/Balanced-Mini-Batches

I'll add a test in an upcoming PR.
