### ISSUE TITLE
ArrayIndexOutOfBoundsException in reshape

### ISSUE THREAD

**Issue by Jajawah** [deeplearning4j/nd4j#1230]
```
INDArray a = Nd4j.linspace(1, 2, 12).reshape(12);
```
I know, this code is non-sense ;)

```
INDArray a = Nd4j.linspace(1, 2, 12).reshape(2, 3, 2);
INDArray b = Nd4j.linspace(3, 4, 4).reshape(2, 2);
int[][] axes=new int[2][];
axes[0]=new int[]{0,2};
axes[1]=new int[]{0,1};
INDArray c=Nd4j.tensorMmul(a, b, axes);
```
This one raise the same bug... and maybe is a non-sense too ;)

**Comment by agibsonccc** [comment]
Did you try 1,12? We don't allow 1d vectors jfyi.

**Comment by Jajawah** [comment]
yes I know, the first example is just to point the non catched exception.
In fact, I got the bug by trying to find how the tensorMmul works.

**Comment by eraly** [comment]
This is what is going on...
INDArray c=Nd4j.tensorMmul(a, b, axes);
So axes[0] applies to a and axes[1]  to b. Essentially they both do a sum along dimensions specified and then do a product. 

Let's consider what happens when you do a sum on a matrix of size (2,3,2) along dimensions (0,2). It returns a vector of size 3 and the assumption here is that it returns a row vector NOT a column vector. I don't think there is anything wrong with this assumption.  

The other matrix b of size(2,2) reduced along (0,1) becomes a scalar of size 1x1.  And trying to multiply these two throws an error. So there are a couple of things you could do.

1. INDArray a = Nd4j.linspace(1, 2, 12).reshape(2, 3, 2,1). This will force it to return a column vector (so you have explicitly specify it) and then carry on whatever else...

2. The other thing is to switch the order of your tensormmul to do Nd4j.tensormmul(b,a,axesNew).
And then BOOM here I found a legitimate bug which I fixed and will be in current master.

So @Jajawah thanks for the issue! Keep 'em coming. We appreciate it.
