### ISSUE TITLE
Garbage collection, memory leak (?), and Yarn containers getting killed

### ISSUE THREAD

**Issue by mbabadi** [deeplearning4j/nd4j#1251]
I have this issue with running my iterative EM algorithm that heavily use Nd4j on Spark. I have properly set javacpp maxBytes, the executor overhead (off-heap memory + some legroom), and executor JVM memory as described in http://deeplearning4j.org/spark; I even took a step further and used a much higher overhead but my containers get killed eventually with a javacpp out of memory exception:

```
...
Caused by: java.lang.OutOfMemoryError: Cannot allocate 9999976240 + 303360 bytes (> Pointer.maxBytes)
	at org.bytedeco.javacpp.Pointer.deallocator(Pointer.java:484)
	at org.bytedeco.javacpp.Pointer.init(Pointer.java:118)
	at org.bytedeco.javacpp.DoublePointer.allocateArray(Native Method)
	at org.bytedeco.javacpp.DoublePointer.<init>(DoublePointer.java:68)
	at org.nd4j.linalg.api.buffer.BaseDataBuffer.<init>(BaseDataBuffer.java:452)
	at org.nd4j.linalg.api.buffer.DoubleBuffer.<init>(DoubleBuffer.java:52)
	at org.nd4j.linalg.api.buffer.factory.DefaultDataBufferFactory.createDouble(DefaultDataBufferFactory.java:228)
	at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:1205)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:243)
...
```

**Comment by mbabadi** [comment]
@saudet looking at the code for deallocator https://github.com/bytedeco/javacpp/blob/master/src/main/java/org/bytedeco/javacpp/Pointer.java#L525 I'm afraid I have a hard time understanding it -- is there a finalizer that changes the while(...) condition? by the way, I am using nd4j-0.5.0 and I believe it is packaged with an older version of javacpp (the latest Pointer.java on javacpp repo is more sophisticated).

**Comment by mbabadi** [comment]
@AlexDBlack, I heard from @raver119 that you have been looking at this issue. I'd appreciate if you could share what you've found -- did you run into a similar issue?

**Comment by mbabadi** [comment]
My code is built with nd4j-0.5.0 and it is run on Google Dataproc (Spark 1.6 on Yarn, AMD64 machines, 40 x 16 vnodes, 40 x 60g total memory, maxbytes=10g, executor JVM heap memory=8g, executor overhead memory=16g). The application manager can get away with killed containers once in a while and recover from the trauma, though it crashes most often after a while :) increasing overhead memory to 20g (=2 x maxBytes) helps, but it eventually runs into the same problem if I let it run for long enough iterations.

**Comment by treo** [comment]
The GC for ND4J works with weak references, so whenever the GC frees up the reference on the Java Side, JavaCPP follows and clears up the off-heap memory reference.

Using `-XX:+UseConcMarkSweepGC` or `-XX:+UseG1GC` you can get a GC that will run more often on its own. The area you have linked to in JavaCPP tries to ask the System for a GC, but it doesn't have to run within those 100ms that the Thread is waiting there, especially when you have large heaps.

I suggest you try a different GC and see if it works better that way for you.

**Comment by mbabadi** [comment]
Thanks @treo, I'll give it a shot. Regarding JavaCPP Pointer -- what I don't understand is how calling gc() changes the loop conditional. I suppose DataBuffers have finalizers that update `DeallocatorReference.totalBytes` (or `r.bytes`) as they are marked for garbage collection. That's the only scenario where retrying gc() can make something happen to the loop conditional. Otherwise, if `maxBytes > 0 && DeallocatorReference.totalBytes + r.bytes > maxBytes` to begin it, it always remains like that no matter how many gc() calls are made, and the OOM exception will be thrown anyway.

ps> nd4j-0.5.0 is built with an older version of JavaCPP. The latest JavaCPP Pointer code has the extra `|| (maxPhysicalBytes > 0 && (lastPhysicalBytes = physicalBytes()) > maxPhysicalBytes))` conditional in the gc() calling loop.

**Comment by mbabadi** [comment]
@tre +UseG1GC was very slow and actually worse! -XX:+UseConcMarkSweepGC didn't help either.  I am thinking of a temporary solution of checkpointing RRDs to HDFS, killing executors every ~ 5 iterations, and restarting them with a fresh JVM heap.

**Comment by saudet** [comment]
That should be fixed with the latest additions to JavaCPP: https://github.com/bytedeco/javacpp/commit/851583a17e176733ec4b822f3b387184c9f15ccb
Basically it now monitors physical memory used. It defaults to a maximum of `2 * Runtime.maxMemory()` so try to set the memory limit of YARN accordingly and containers shouldn't get killed anymore.

**Comment by AlexDBlack** [comment]
@mbabadi first up: are you caching your data? .cache() or .persist(StorageLevel.MEMORY_ONLY()) or .persist(StorageLevel.MEMORY_AND_DISK())?
Spark's memory management (i.e., when to drop blocks etc) leaves a *lot* to be desired when it comes to off-heap memory. I've run into OOMs before due to that. Feel free to PM me on gitter if you want the full technical details.
I really need to get some docs up on that.

If you are caching, try StorageLevel.MEMORY_ONLY_SER() or StorageLevel.MEMORY_AND_DISK_SER() instead, and see if the problem remains.

**Comment by mbabadi** [comment]
@AlexDBlack thanks for your reply! yes, I cache a lot indeed as I have an iterative algorithm that requires a certain degree of back and forth between the executors and the driver in each iteration. I also unpersist old caches when I don't need them anymore and checkpoint to disk every now and then to cut the DAG lineage; I think now I see what the problem is: since the caches are stored in deserialized from by default, the references remain alive and don't get garbage collected. Am I right? I just started a new run with StorageLevel.MEMORY_ONLY_SER() and it is going strong so far. I will report back if it completes without OOM exceptions.

**Comment by mbabadi** [comment]
@AlexDBlack the caches are now serialized:
![spark](https://cloud.githubusercontent.com/assets/15305869/18183693/86103870-7063-11e6-9e30-46368ac68958.png)
I don't see much of a slowdown either, even though in theory, serialized cached RDDs must be slower as they need to be deserialized upon access, right? but I suppose, as your said, perhaps this is the best one can do due to limitations of Spark's memory management.

ps> I think unpersist() is lazy by default; it just marks the caches for deletion. I often noticed that the old caches get deleted progressively (i.e. going down from 100% to 0% bit by bit). I wonder whether calling unpersist(true) (w/ blocking) would allow one to use StorageLevel.MEMORY_ONLY() and still not run into OOM?

pps> using StorageLevel.MEMORY_ONLY_SER() did improve memory usage quite a bit but I still get  OOM, though at iteration 20 (I used to get OOM at iteration 10).

**Comment by saudet** [comment]
@mbabadi If garbage collection takes too much time, JavaCPP will just give up, so maybe that's the issue? Try to increase http://bytedeco.org/javacpp/apidocs/org/bytedeco/javacpp/Pointer.html#maxRetries

**Comment by mbabadi** [comment]
@AlexDBlack using unpersist(true) did the trick, I completed a full run (40 iterations) without a single container getting killed!
@saudet I will set it to 100 for good measure, thanks! in fact I thought about increasing maxretries a while ago but I forgot :)

You guys rock, thank you all!

@AlexDBlack let me know if you need a hand in updating dl4j spark docs.

**Comment by AlexDBlack** [comment]
@mbabadi "since the caches are stored in deserialized from by default, the references remain alive and don't get garbage collected. Am I right?"
Exactly. Spark will keep as much in memory as possible (to avoid recomputing full lineage), based on how big it things the objects are.
It estimates the size by walking the java object graph; consequently it doesn't consider the off-heap data size at all.
INDArrays and DataSets are pretty much entirely off-heap.
Consequently, it keeps too much in memory (because the *on-heap* size is small, it's not dropping blocks when required), leading to OOM issues.
In serialized form, it's all on-heap however, and spark can actually estimate the size properly as a result.

"let me know if you need a hand in updating dl4j spark docs."
Thanks for the offer. I'll hopefully get to that maybe today or tomorrow.
I shouldn't need to add much, but it'd be great to have someone review it after, make sure it makes sense and is easy to understand. I'll ping you once it's done.

**Comment by AlexDBlack** [comment]
@mbabadi new docs with caching info is up: http://deeplearning4j.org/spark#caching
