### ISSUE TITLE
recent Jackson version requires shading

### ISSUE THREAD

**Issue by huitseeker** [deeplearning4j/nd4j#1293]
Two emplacements require jackson 2.5.1:
https://github.com/deeplearning4j/nd4j/blob/master/pom.xml#L251
https://github.com/deeplearning4j/nd4j/blob/master/nd4j-serde/nd4j-jackson/pom.xml#L9

Spark and other downstream projects only play nice with 2.4.4. shading with e.g. maven-shade is probably needed if those versions are crucial ( see also https://github.com/deeplearning4j/DataVec/pull/64 )

**Comment by agibsonccc** [comment]
This is going to be fixed here soon /cc @AlexDBlack has been working on this the past few days.

**Comment by AlexDBlack** [comment]
Yeah, there's actually a PRs open that shade Jackson for nd4j, dl4j, datavec, but I'm going to replace that with a different design.
The plan is to shade things once, then pull that in everywhere (so one interoperable shaded version of jackson across all projects, rather than a separate shaded version of jackson per project).
Also doing the dropwizard stack too (jersey, jetty, etc) so we can use that + spark is the same JVM.

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/nd4j/pull/1294
That adds org.nd4j.shade.jackson as a dependency; now using that throughout DL4J, ND4J and DataVec in favour of 
I also tried to shade Dropwizard for use in DL4J and Arbiter, but that is proving more difficult. That will be in a separate PR later.
