### ISSUE TITLE
Cuda Backend: Cache reuse problem (Some kind of memory leak)

### ISSUE THREAD

**Issue by mjakobus** [deeplearning4j/nd4j#1506]
Hi @raver119 ,

I found out, why the device side caching with cuda is sometimes causing problems / a memory leak in device memory.
As I already mentioned in deeplearning4j #2422 with x-fold crossvalidation training in last folds the device cache hit ratio shrinks and thus the performance heavily suffers, although all data of every fold should easily fit in the vram. In gpu-z I saw, that every new fold is adding memory consumption on top of the existing memory. This resulted in the bad cache hit ration in the last folds.
The last days I tried to reproduce this behavior in an example, but I wasn't successful. 
Finally I found the cause of this reuse problem. It seems, that the device cache can't get reused if the DataSets/INDArray has a different size than the one for which the space in the vram was allocated and thus additional space gets allocated. If this happens a few times the vram fills up fast and most space of the vram is blocked.

I'have created an example in which you can reproduce this behavior. The example simulates a x-fold training by creating random training data, creating a MultiLayerNetwork and train this network with batch-training for 10 epochs. This training happens in a loop.
With the variable "useVaryingBatchSize" at the top you can control, if always the same batch size (1000) should be used (useVaryingBatchSize=false), or if for every training loop passage an other batch size is used. Instead of randomly changing the batch size I have defined a list with 10 different batch sizes, which get used one after another for each training. After the tenth training he is using the first batch size again.
All other settings (Cache sizes...) are on default. On my device (GTX 1080) these default settings are using up to 2,5GB of the vram. 

**useVaryingBatchSize=false:**
With the same batch size you will even after the 50th training loop have the same speed as in the first training iteration. There is still some space left in the vram until reaching the 2.5GB and the device cache hit ratio is always about 99%

**useVaryingBatchSize=true:**
With varying the batch size the first three or four training loop passages are fast, but then the vram is filled with 2.5GB of data and the performance and device cache hit ratio suffers heavily. Now to the reason whys I'm using an array of batch sizes: After the tenth training iteration, the program is again using the first batch size from the list for the eleventh training loop. Using this first batch size again it seems that the device cache can get used again and the training is back at full speed. For the following training loops it is then again continuously slowing down.
With a completely random batch size this would even be worse.

**The example:**
https://gist.github.com/mjakobus/ab02804d3cbc0526c4d8286189c73fe0

**System details:**
dl4j 0.7.1
GTX 1080
Cuda 8.0 Backend
Windows 10 64-bit

**Comment by raver119** [comment]
Technically you're right, but it's not a leak: current allocation/cache implementation favours equal sized memory allocations. And no, there's no fast solution for this i could suggest. It's just a logic limitation of current mechanic.

Even if i add something like LRU mechanic for cache, it won't really improve performance, because you'll always have chance that allocation request won't be served from cache, and real cudaMalloc will be issued, which is still very expensive call. And since your DataSet will have totally new shape, all ops applied/derived from this DataSet will have new dimensions, and won't be served from cache as well. So they will be served from device directly (via cudaMalloc/HostAlloc) as well, and thus will be slow.

Obviously, it's kinda possible to provide own allocation mechanism, like allocate 1-4GB of device RAM, and manage allocations manually via "pointer magic", but right now we're not set for this approach, and JVM GC issue is higher priority right now.

**Comment by mjakobus** [comment]
Aren't there even any possibilities to create a method like "resetCudaCache"? Something which allows to reset the allocated cache to get a fresh vram state, like it is when the program has just started or when using the DIRECT AllocationMode? This would already help a lot.
Otherwise it is impossible to do the training of several networks after another, without always restarting the program and thus automated cross validation and hyperparameter search gets really hard.

Of course I understand, that there are a issues with a higher priority, but why closing this issue and not just leave it in the backlog?

Besides I wonder if the Arbiter is not also affected by this issue, since it seems that the candidates get also trained in a loop?

**Comment by raver119** [comment]
Well, there IS such method, but it's ***HIGHLY*** unrecommended to use.

There's multiple cache mechanisms implementing there, and reset will actually reset both of them, including device constant memory. That method is used for development/debugging purposes and i'm not ready to say it's "safe" to use in wild life.

re: closed issue. Sure i can open this one back again if you want, but it won't really change anything. This issue IS known, it IS going to be fixed/improved _somehow_, but it's way below most important thing for now: JVM GC & memory deallocation process.

**Comment by raver119** [comment]
Workspaces are coming to dl4j now: https://github.com/deeplearning4j/nd4j/pull/1731

Hypothetically overallocation configuration should resolve this issue in arbiter.
