### ISSUE TITLE
DataSetUtil.setMaskedValuesToZero doesn't work

### ISSUE THREAD

**Issue by EdeMeijer** [deeplearning4j/nd4j#1538]
```java
import org.nd4j.linalg.api.ndarray.INDArray;
import org.nd4j.linalg.dataset.api.DataSetUtil;
import org.nd4j.linalg.factory.Nd4j;

import java.io.IOException;

public class Test {
    public static void main(String[] args) throws IOException {
        INDArray data = Nd4j.create(new float[]{1, 2, 3, 4, 5, 6}).reshape(2, 1, 3);
        INDArray mask = Nd4j.create(new float[]{1, 1, 0, 1, 0, 0}).reshape(2, 3);

        DataSetUtil.setMaskedValuesToZero(data, mask);

        System.out.println(data);
    }
}
```

outputs
```
[[0.00, 2.00, 3.00],

 [4.00, 5.00, 6.00]]
```

while I expected
```
[[1.00, 2.00, 0.00],

 [4.00, 0.00, 0.00]]
```

This thing is used in all the normalizers, so that's a problem.

**Comment by eraly** [comment]
@raver119 ?

**Comment by raver119** [comment]
As explained in dev_channel, that's broken TAD calculation - edge case with ones in original shapeInfo. @agibsonccc  knows something about this bug

Additional info:
op.X shape: [3, 2, 1, 3, 3, 3, 1, 0, 1, 99]; 
native TAD: [2, 1, 1, 1, 1, 0, 1, 0]; 
jvm TAD: [2, 2, 3, 3, 1, 0, -1, 99]

So, native TAD calculation goes mad when meets one in shapeInfo

Also, this issue is definitely related to this one: https://github.com/deeplearning4j/nd4j/issues/1525

**Comment by EdeMeijer** [comment]
Okay, good that you know what's up. Let me know if you need anything.

**Comment by agibsonccc** [comment]
Overhaul on this inc. I have an idea of the incompatibilities now.

**Comment by agibsonccc** [comment]
@eraly could you confirm this is fixed?

**Comment by agibsonccc** [comment]
This has been fixed with new TAD
