### ISSUE TITLE
nd4j-backed docs

### ISSUE THREAD

**Issue by tomthetrainer** [deeplearning4j/nd4j#1623]
I will need some help on this because I found myself confused when I went to deploy a jar built on one platform (mac) onto another (ubuntu) . 

I would like to either move documentation if we have it, or create documentation if we don't on the choices, meanings and use of the nd4j backend settings. 

    <groupId>org.nd4j</groupId>
                <artifactId>nd4j-native-platform</artifactId>
                <version>${nd4j.version}</version>
            </dependency>
            <dependency>
                <groupId>org.nd4j</groupId>
                <artifactId>nd4j-cuda-7.5-platform</artifactId>
                <version>${nd4j.version}</version>
            </dependency>
            <dependency>
                <groupId>org.nd4j</groupId>
                <artifactId>nd4j-cuda-8.0-platform</artifactId>
                <version>${nd4j.version}</version>

@raver119 Adding you because I think this is your domain, if wrong add whoever is right.

**Comment by raver119** [comment]
Well, -platform artifacts were created by Sam exactly for that purpose - they contain binaries for all possible platforms we support. So when user has, say. nd4j-native-platform in dependencies, his app should run fine everywhere.

However, when someone builds whole stack from sources - platform artifacts are NOT available obviously, because in 99% of cases user will build from sources on his only local box.

**Comment by raver119** [comment]
As of available options:

- nd4j-native: pure cpu + OpenMP + OpenBLAS backend (however it's possible to use MKL or whatever else)
- nd4j-cuda-7.5: CUDA backend compiled against nVidia CUDA 7.5 library
- nd4j-cuda-8.0: CUDA backend compiled against nVidia CUDA 8.0 library

So, when user wants to use CUDA backend - he should install nVidia CUDA Toolkit (available from nVidia website) version either 7.5 or 8.0 (which is current atm), and then use appropriate nd4j-cuda-X.X backend
