### ISSUE TITLE
SplitTrainandTest for MultiDataSet

### ISSUE THREAD

**Issue by AJku7** [deeplearning4j/nd4j#1650]
Hello I was wondering Multi Dataset has no support for SplitTrainandTest.
adding this support would be helpful

**Comment by raver119** [comment]
@AlexDBlack i guess this is still viable?

**Comment by AlexDBlack** [comment]
hm... yeah. We've got asList and the like (list, shuffle, sublist, merge can be used to implement this manually), but this specific method hasn't been implemented.
Though I've never really liked DataSet.splitTrainAndTest (it encourages users to load all their data into memory, rather than splitting earlier in the pipeline). So I'm kind of on the fence as to whether we implement it at all.

**Comment by raver119** [comment]
Let's just close this issue then?
