### ISSUE TITLE
Add ability to flatten arrays

### ISSUE THREAD

**Issue by crockpotveggies** [deeplearning4j/nd4j#1831]
#### Issue Description

After some investigation we lack the ability to flatten arrays. This is necessary if we want to do interesting operations such as the equivalent of [reshape](https://www.tensorflow.org/api_docs/python/tf/reshape) or [view](https://github.com/torch/nn/blob/master/View.lua).

#### Version Information

Master, lastest everything, etc.

#### Contributing

If @raver119 or someone else can show me the relevant code, I can tackle this.

**Comment by raver119** [comment]
Nd4j.toFlattened() isn't enough?

**Comment by crockpotveggies** [comment]
Quite possibly, does that match the underlying functionality in the layers mentioned in the links above? If so, I can probably just write a DL4J vertex for this.

**Comment by AlexDBlack** [comment]
In practice, flattening means making a row vector.
However – there are multiple ways to do this: notably C order or F order. That's why we have reshape with order and flatten with order operations (i.e., .toFlattened(char), .reshape(char, int[])).

I would imagine that Tensorflow probably decides on a single order – most likely C – for all operations like this. A DL4J Vertex for this should be straightforward – though keep in mind the performance impact of flattening a C order array to F order and vice versa.

**Comment by AlexDBlack** [comment]
Closing this - seems like we have all the functionality we need
