### ISSUE TITLE
ND4J Initialization fails with Access Control Exception for "getenv.*"

### ISSUE THREAD

**Issue by bazinga29** [deeplearning4j/nd4j#2519]
#### Issue Description

While initializing ND4J, I see runtime exception stating access was denied to getenv.*

By adding Runtime permission to getenv.*, it gives access to ALL environment variables which is not very secure.

Expected Behavior: Exceptions can be thrown asking for access permissions to access specific environment variables instead of all env variables.

Exception:
Caused by: java.lang.RuntimeException: java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "getenv.*")
	at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:6212)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:6087)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:201)
	... 43 more
Caused by: java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "getenv.*")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
	at java.security.AccessController.checkPermission(AccessController.java:884)
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
	at java.lang.System.getenv(System.java:944)
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.<init>(NativeOpExecutioner.java:73)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:6185)
	... 45 more

#### Version Information
0.9.1

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: 0.9.1
* platform information (OS, etc): macOS Sierra 10.12.6, Eclipse IDE, JDK 1.8.0_121
* CUDA version, if used - I am not using CUDA
* NVIDIA driver version, if in use - N/A

**Comment by saudet** [comment]
And what prevents you from giving it access to only some environment variables?

**Comment by gagatust** [comment]
https://github.com/deeplearning4j/nd4j/blob/ed7fcf8242a0165907b3a25fa3ca61082c60eeaf/nd4j-backends/nd4j-backend-impls/nd4j-native/src/main/java/org/nd4j/linalg/cpu/nativecpu/ops/NativeOpExecutioner.java#L77
https://github.com/deeplearning4j/nd4j/blob/ed7fcf8242a0165907b3a25fa3ca61082c60eeaf/nd4j-backends/nd4j-backend-impls/nd4j-cuda/src/main/java/org/nd4j/jita/conf/Configuration.java#L212

**Comment by saudet** [comment]
Great, thanks! So, we only need to change these 2 places? Mind sending a pull request? :)

**Comment by raver119** [comment]
You're looking into almost full list. I think the only variable missing here is ND4J_FALLBACK and GPU/CPU priorities.

Re: why environment vars? Because it's really trivial to set those. I.e. to enable debug mode, or to switch backends etc.

**Comment by gagatust** [comment]
ND4J_SKIP_BLAS_THREADS
ND4J_FALLBACK
ND4J_PREVENT_UNPACK
DYNAMIC_LOAD_CLASSPATH
BACKEND_PRIORITY_CPU
BACKEND_PRIORITY_GPU
SPARK_PUBLIC_DNS
DL4J_VOID_IP
OMP_NUM_THREADS
PATH_ENV_VARIABLE

If all programs stored their settings in the environment vars, it would not be very good because we would have thousands of settings in one place. 
Why are there so many different places with settings? All of them load and parse. I think it will be better to have the one for load, parse and store all settings.

https://github.com/deeplearning4j/nd4j/blob/ed7fcf8242a0165907b3a25fa3ca61082c60eeaf/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/factory/Nd4j.java#L6317-L6337
https://github.com/deeplearning4j/nd4j/blob/ed7fcf8242a0165907b3a25fa3ca61082c60eeaf/nd4j-backends/nd4j-api-parent/nd4j-native-api/src/main/java/org/nd4j/nativeblas/Nd4jBlas.java#L22-L24
https://github.com/deeplearning4j/nd4j/blob/ed7fcf8242a0165907b3a25fa3ca61082c60eeaf/nd4j-backends/nd4j-api-parent/nd4j-native-api/src/main/java/org/nd4j/nativeblas/NativeOpsHolder.java#L34-L37
https://github.com/deeplearning4j/nd4j/blob/ed7fcf8242a0165907b3a25fa3ca61082c60eeaf/nd4j-backends/nd4j-backend-impls/nd4j-cuda/src/main/java/org/nd4j/jita/conf/Configuration.java#L212-L221
https://github.com/deeplearning4j/nd4j/blob/ed7fcf8242a0165907b3a25fa3ca61082c60eeaf/nd4j-backends/nd4j-backend-impls/nd4j-native/src/main/java/org/nd4j/linalg/cpu/nativecpu/ops/NativeOpExecutioner.java#L77-L86
https://github.com/deeplearning4j/nd4j/blob/ed7fcf8242a0165907b3a25fa3ca61082c60eeaf/nd4j-common/src/main/java/org/nd4j/linalg/util/Paths.java#L45
https://github.com/deeplearning4j/nd4j/blob/ed7fcf8242a0165907b3a25fa3ca61082c60eeaf/nd4j-context/src/main/java/org/nd4j/linalg/factory/Nd4jBackend.java#L76-L84
https://github.com/deeplearning4j/nd4j/blob/ed7fcf8242a0165907b3a25fa3ca61082c60eeaf/nd4j-parameter-server-parent/nd4j-parameter-server-node/src/main/java/org/nd4j/parameterserver/distributed/VoidParameterServer.java#L337-L347
https://github.com/deeplearning4j/nd4j/blob/ed7fcf8242a0165907b3a25fa3ca61082c60eeaf/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/environment/Nd4jEnvironment.java#L35-L60

Files with "System.getpro" string:
BackgroundDaemonStarter.java
BaseNd4jTest.java
BinarySerdeTest.java
ContextHolder.java
CudaDataBufferFactory.java
CudaFloatDataBufferTest.java
DefaultDataBufferFactory.java
DefaultOpExecutioner.java
DelayedMemoryTest.java
Environment.java
EnvironmentUtils.java
ExecutorServiceProvider.java
LibUtils.java
LogInspector.java
MiniBatchFileDataSetIterator.java
NativeOpsHolder.java
Nd4j.java
Nd4jBackend.java
Nd4jContext.java
Nd4jTestsC.java
Nd4jTestSuite.java
ParameterServerSubscriber.java
TestUtils.java
VersionCheck.java
