### ISSUE TITLE
Bounding (0 to 1) loss function

### ISSUE THREAD

**Issue by tom-adsfund** [deeplearning4j/nd4j#2596]
Feature request:

Implement a loss function for regression that heavily penalizes values outside of the range 0 to 1. The idea is to test the proposition that this might be better for estimating probabilities than a usual sigmoid output.

**Comment by AlexDBlack** [comment]
I'm closing this. Give me a paper/reference for a specific loss function that does this and we'll definitely consider it - otherwise, this is why we support custom los functions. We're not going to develop and implement something for the core library speculatively, when there's no basis in the literature for it.
