### ISSUE TITLE
Random CUDA Crash

### ISSUE THREAD

**Issue by treo** [deeplearning4j/nd4j#2635]
I've ran into a seemingly random cuda crash. It worked fine for some 3000 iterations and then crashed:
[hs_err_pid15880.log](https://github.com/deeplearning4j/nd4j/files/1720696/hs_err_pid15880.log)

Workspace is set to WorkspaceMode.NONE for both inference and training.

**Comment by AlexDBlack** [comment]
I'm going to close this - it's very likely fixed:
https://github.com/deeplearning4j/Arbiter/issues/141
https://github.com/deeplearning4j/libnd4j/pull/784

The above arbiter issue was ultimately caused by a pullRows bug, which occured in reverseTimeSeries (as per your crash log). That also occurred irrespective of workspace mode.
