### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by renato2099** [deeplearning4j/nd4j#274]
After pulling the latest changes from Nd4s and Nd4j we can't do map operations over INDArrays.
A gist showing the problem can be found in here:
https://gist.github.com/renato2099/3837bdf20680799ebbbe

**Comment by renato2099** [comment]
Hi @taisukeoe, could you help us taking a look at this please?

**Comment by taisukeoe** [comment]
`org.nd4j.linalg.api.ops.Op` which underlies `map` supports only operations from Float | Double to Float | Double, or from IComplexNumber to IComplexNumber.

Since `tensor.map(p => println(p))` stands for operations from `Double` to `Unit` as `println` function returns `Unit`, it doesn't satisfy above type requirement and then shows compilation error.

So the following alternatives should compile.

```scala
/*
though I'm not sure why p needs to be println, 
since println has side-effects: printing p to Standard Output, which takes a bit time.
*/
tensor.map{p => println(p);0} 
```

or 

```scala
/* 
this is more meaningful if you want to check the real time of mapping, 
without side effects like printing.
*/
tensor.map(_ + 1) 
```

**Comment by agibsonccc** [comment]
Thanks @taisukeoe Maybe you could put a feature request describing what you'd like to happen? One obvious feature here could be map/filter over dimensions and indexes and the like.
