### ISSUE TITLE
Problem with raw data: getRow(idx).data().asDouble()

### ISSUE THREAD

**Issue by jarekkar** [deeplearning4j/nd4j#2771]
#### Issue Description
When I try to get raw data from row vector (``getRow(idx).data().asDouble()``) I got double[] array with incorrect length. For more details let's consider following code:

**Code:**
```
int rows = 8;
int columns = 2;
INDArray array = Nd4j.zeros(rows, columns);
Log.e("array", array.toString());

INDArray firstRow = array.getRow(0);
Log.e("first row", firstRow.toString());

DataBuffer dataBuffer = firstRow.data();
Log.e("data buffer", dataBuffer.toString());

double[] rawData = dataBuffer.asDouble();
Log.e("raw data", Arrays.toString(rawData));
```
**Output:**
```
array: [[0.00, 0.00],
        [0.00, 0.00],
        [0.00, 0.00],
        [0.00, 0.00],
        [0.00, 0.00],
        [0.00, 0.00],
        [0.00, 0.00],
        [0.00, 0.00]]
first row: [0.00, 0.00]
data buffer: [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0]
raw data: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
```
In this case raw data array has sixteen elements. Is it correct?

Let's consider next piece of code (the same instructions on submatrix):

**Code:**
```
INDArray subarray = array.get(NDArrayIndex.interval(1, array.rows()), NDArrayIndex.all());
Log.e("subarray", subarray.toString());

firstRow = subarray.getRow(0);
Log.e("first row", firstRow.toString());

dataBuffer = firstRow.data();
Log.e("data buffer", dataBuffer.toString());

rawData = dataBuffer.asDouble();
Log.e("raw data", Arrays.toString(rawData));
```
**Output:**
```
subarray: [[0.00, 0.00],
           [0.00, 0.00],
           [0.00, 0.00],
           [0.00, 0.00],
           [0.00, 0.00],
           [0.00, 0.00],
           [0.00, 0.00]]
first row:: [0.00, 0.00]
buffer: [0.0,0.0]
raw data: [0.0, 0.0]
```
In this case raw data array has two elements. Which behavior is correct?

#### Version Information

* Nd4j version: 0.8.0
* Android 7.0

**Comment by treo** [comment]
`getRow(i)` usually results in a view. So if you want to get just the data of that view, you will have to do it like that: 
`getRow(idx).dup().data().asDouble()`.

the `.get` -> `.getRow` case works only because of a special case handling, where it would have resulted in a view on a view, and you basically got the `dup()` done for you at some point.

Basically, if you want to get data as a double[] you shoul always use `.dup()`, as only that will guarantee you that the INDArray you are calling `data().asDouble()` on, will be pointing to just the data that you want.

**Comment by jarekkar** [comment]
Thanks :-)
