### ISSUE TITLE
Conv2d crash

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#2835]
The following code crashes on 1.0.0-alpha

```
        int nIn = 1;
        int nOut = 1;
        int kH = 4;
        int kW = 3;

        int mb = 1;
        int imgH = 256;
        int imgW = 256;

        SameDiff sd = SameDiff.create();
        INDArray wArr = Nd4j.ones(nOut, nIn, kH, kW); //As per DL4J
        wArr = wArr.mul(3);
        System.out.println(Arrays.toString(wArr.shape()));

        INDArray inArr = Nd4j.ones(mb, nIn, imgH, imgW);
        inArr = inArr.mul(5);
        System.out.println(Arrays.toString(inArr.shape()));

        SDVariable in = sd.var("in", inArr);
        SDVariable w = sd.var("W", wArr);
//        SDVariable b = sd.var("b", Nd4j.create(1));

        //Order: https://github.com/deeplearning4j/libnd4j/blob/6c41ea5528bb1f454e92a9da971de87b93ff521f/include/ops/declarable/generic/convo/conv2d.cpp#L20-L22
        //in, w, b - bias is optional
        SDVariable[] vars = new SDVariable[]{in, w};
//        SDVariable[] vars = new SDVariable[]{in, w, b};

        Conv2DConfig c = Conv2DConfig.builder()
            .kh(kH).kw(kW)
            .ph(0).pw(0)
            .sy(1).sx(1)
            .dh(1).dw(1)
            .isSameMode(true)
            .isNHWC(false)
            .build();

        SDVariable out = sd.conv2d(vars, c);

        INDArray outArr = sd.execAndEndResult();
        System.out.println(Arrays.toString(outArr.shape()));
```

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x0000000069545a2f, pid=9388, tid=0x0000000000003e2c
#
# JRE version: Java(TM) SE Runtime Environment (8.0_151-b12) (build 1.8.0_151-b12)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.151-b12 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [libnd4jcpu.dll+0xc5a2f][thread 9656 also had an error]

#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
[thread 14240 also had an error]
# An error report file with more information is saved as:
# C:\DL4J\Git\dl4j-examples\hs_err_pid9388.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

https://gist.github.com/AlexDBlack/2033e30aaf0feb6cc99a24a4e8dcd5f1

**Comment by shyrma** [comment]
Hmm..
Quick analysis shows that one can avoid crash setting isSameMode = false

**Comment by shyrma** [comment]
More detailed analysis showed that reason of crash was integer overflow (case when product of integers becomes > INT_MAX).
This overflow happened during shape permutation in following function:
https://github.com/deeplearning4j/libnd4j/blob/d340da4109c8175cd5e64704f42831c675416650/include/helpers/shape.h#L2699
and since your test provides large strides {786432, 786432, 196608, 65536, 256, 1}, 
function shape::prodLong
https://github.com/deeplearning4j/libnd4j/blob/d340da4109c8175cd5e64704f42831c675416650/include/helpers/shape.h#L2583
produces strides product which is definitely bigger then INT_MAX.

Because shape::functions code was written before I stared work in skymind, I informed raver about this issue.
He answered he is acquainted with this problem and already fixed it some time ago.
But unfortunately his fix hasn't survived during regular master branch updates somehow O_o.
Since raver is traveling currently, I provided another function which performs shape_info permutation (branch shyrma_refactoring_1) 
and it fixes the problem of integer overflow:
https://github.com/deeplearning4j/libnd4j/blob/9da191a79fb74e9c536bf0872f867b904e285611/include/helpers/shape.h#L2654

**Comment by AlexDBlack** [comment]
@shyrma I'm assuming this isn't yet fixed on libnd4j master now?
i.e., it's still pending here: https://github.com/deeplearning4j/libnd4j/pull/862

If so, I'll keep this open until it's merged.
(also, when I closed issues, I like to add a link to the PR and a status updated - i.e., "fix merged here" or "fixed on branch X which will be merged soon")

**Comment by shyrma** [comment]
Alex
>I'm assuming this isn't yet fixed on libnd4j master now
Yes, that is true. 
Now I understand  when the issue can be closed :-)
I simply thought one can close issue when it is fixed in some branch, not necessary in master.
So, ok, let wait until raver merges my branch into master.

**Comment by AlexDBlack** [comment]
Thanks. Yeah, by convention we *usually* close issues only when stuff is merged (with the occasional exception - i.e., "I'll be merging this in the next few hours"). Basically if you can still run into the problem on master, an issue should be open IMO.

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/libnd4j/pull/862
