### ISSUE TITLE
Shape mismatch

### ISSUE THREAD

**Issue by whilo** [deeplearning4j/nd4j#424]
Hey,

while working with clj-nd4j we hit this issue:

```clojure
(vec (.shape (Nd4j/create (double-array [1 2]) (int-array [2]) (int-array [1]) 0 \c))) ; => [1 2]
```
but the shape should be just `[2]` as passed to the static factory method. Any hints/ideas?

**Comment by agibsonccc** [comment]
Could you clarify the issue a bit? Is it a stack trace problem? (I'm not a clojure guy but will help as best as I can.

**Comment by whilo** [comment]
No, it is just that we define the shape as `[2]` as the second argument and `.shape` returns `[1 2]` for some reason. Maybe I call `Nd4j.create` wrong?

**Comment by agibsonccc** [comment]
Please use Nd4j.create(1,2);

I've chosen to force all behavior to only work with 2d for vectors,scalars,
and matrices.

It just makes life easier.
ᐧ

**Comment by whilo** [comment]
You mean all ndarrays are in fact matrices? So `[[1 2]]` is not distinguishable from `[1 2]`?

**Comment by agibsonccc** [comment]
No. We have isVector() and the like. We also distinguish column vectors/scalars with isScalar()

We force everything to be 2d. There are a lot of special cases with 1d. we fix. I'm going to close this. You can go ahead and submit an opinion about how things should be done but that's a separate issue since this appears to be a clarification.
