### ISSUE TITLE
ND4J.max(z, 1) 

### ISSUE THREAD

**Issue by zhouh** [deeplearning4j/nd4j#560]
Hi all, I found a feature(or bug) of the ND4J.max(z, 1) 
if z is shape{n, n} the function will return a row vector, if z is shape{n, 1} it will return a column vector, but ND4J.argMax(z, 1) will always return a row vector
PS: I used the 3.7 version, I do not test it over the new release
But in a normal way, I should not use the max function if z is shape{n, 1}

**Comment by Zixxy** [comment]
If you mean this:

```
        INDArray arr1 = Nd4j.create(new double[][]{{1, 2, 14, 5}, {3,6, 8,9}});
        INDArray max1 = Nd4j.max(arr1, 1);
        INDArray arr2 = Nd4j.create(new double[][]{{1}, {2}, {14}, {5}});
        INDArray max2 = Nd4j.max(arr2, 1);
        INDArray arr3 = Nd4j.create(new double[][]{{1, 2, 14, 5}});
        INDArray max3 = Nd4j.max(arr3, 1);

```

On current master this code returns:
max1 == [14.00, 9.00], max2 = [1.00, 2.00, 14.00, 5.00], max3 = "14.00" and for me that is correct result. 
Look at first matrix:
1, 2, 14, 5
3, 6, 8, 9
and looking at dimension 1 it retunrs 14, 9
Second:
1
2
14
5
and correct along 1 is [1.00, 2.00, 14.00, 5.00]
Third:
1, 2, 14, 5
and result is 14.

For me it is not a bug. If you want I can push it as test, so that in future it won't appear as bug.

**Comment by zhouh** [comment]
Hi, thanks for your answer.
Sorry for my misleading description of the shape of vectors.
My new adopted release is 0.4-rc3.8.

I means that the result returned by max() along dim 1 should be a consistent shape.
In your test code:
matrix:
1, 2, 14, 5
3, 6, 8, 9
and looking at dimension 1 it returns
14,
9
which is a column vector.
Second:
1
2
14
5
and correct along 1 is [1.00, 2.00, 14.00, 5.00]， which is a row vector!

I think the max operation along dim one should be a column vector, or at least given a input matrix with arbitrarily shape, the returned vector shape should be consistent!

**Comment by agibsonccc** [comment]
Update on this?
