### ISSUE TITLE
Add putScalar overloads with varargs indexing

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#705]
INDArray defines the following putScalar methods:
- putScalar(int[], double)
- putScalar(int[], float)
- putScalar(int[], int)

It would be be more convenient to have the following varargs overloads, so that the user doesn't have to manually create an int[] for indexing:
- putScalar(double, int...)
- putScalar(float, int...)
- putScalar(int, int...)

**Comment by saudet** [comment]
The order of the parameters would be inconsistent with arrays and the `=` operator, as well as typical `put()` methods. BTW, how many dimensions do we need in general? If it's only a small number, it's probably more efficient to define a bunch of overloaded methods, since no temporary arrays get created. Plus, for those cases explicitly defined, we can keep the traditional order of the parameters, e.g.:
```
putScalar(int i, double x)
putScalar(int i, int j, double x)
putScalar(int i, int j, int k, double x)
...
putScalar(int[] idx, double x)
```
And while we're at it, each dimension can never be larger than 2^31-1?

**Comment by AlexDBlack** [comment]
varargs has to be the last parameter if we are using that, hence the reason for that order. And internally I'm sure it would result in an intermediate int[] array by the time an array index is calculated. We don't need that many dimensions, I've only seen up to 6 being used in practice. But putScalar(int,int,int,int,int,int,double) is kinda ugly.

Having dimensions larger than Integer.MAX_VALUE is not currently possible due to integer indexing. Previously this was due to java limitations as you know.

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/nd4j/pull/871
