### ISSUE TITLE
Memory Leaking when using jcublas

### ISSUE THREAD

**Issue by Bam4d** [deeplearning4j/nd4j#74]
With the following snippet, memory allocation grows and grows in RAM and within GPU memory:
```
for(int x = 0; x<1000; x++) {
	INDArray arr = Nd4j.create(3000,3000);
	Thread.sleep(500);
}
```

Looking at the underlying code in jcublas. These memory allocations should be getting cleared up as the loop proceeds.

The memory allocation just keeps on climbing until the GPU crashes and paging starts.

Any idea where the memory leak might be happening? It seems to be happening on both sides...

**Comment by Bam4d** [comment]
This appears to only happen on some cards. 580gtx yes, seems to be fine on a 980gtx. This is probably something to do with pinned memory allocation on older cards perhaps? I'm not entirely sure :/

**Comment by agibsonccc** [comment]
I"m going to try the unified memory (cudaAllocManaged)

**Comment by Bam4d** [comment]
I don't think that the pinned memory allocation was the problem, I'm still getting the leak problem. It's just slower now. I have much more RAM

I found a few issues. I'll do a few fixes and PR them if they are working.

1. the reaper thread can die and then stop forcing system gc and finalize:
```
public void purge() {
        if(currentAllocated() > maxAllocated())
            throw new IllegalStateException("Illegal current allocated: " + currentAllocated() + " is greater than max " + maxAllocated());
```

This check is only performed in the reaping process and not before memory is allocated, meaning the CUDA card can fill up it's memory between purge calls and then the purge() thread crashes.

2. if the INDArray becomes persistent for any reason old-gen etc... System.gc() will not collect it. (thoretically this could happen, I'm not sure how the references end up being in more persistent gen spaces)


Generally I dont think the

**Comment by agibsonccc** [comment]
So looked in to the managed memory..not going to help much. Going to stick with the host allocated/zero copy. You're absolutely right though. My initial aim was to get something working and first sort out the multi host thread/GPU synchronization.  This does make sense. I can look in to that ( a second pair of eyes helps here when I have a lot of things I'm juggling)

**Comment by Bam4d** [comment]
Not  problem. Me and a collegue have been going through this code and think that the best way to solve this is to not use gc/finalize/reference queues, but to manage the memory manually...

Trying to keep the interfaces the same for jblas/cublas might be a bit hard. Maintaining pinned memory between kernels might be a bit of a challenge also... but then we can perhaps use [try with resouces](https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html) perhaps.

code might look a bit like this:
```
try( INDArray array = nd4j.create(1000,1000) ) {
    ..stuff to do with array
}
```

Just some initial thinking on the subject...

**Comment by Bam4d** [comment]
my main goal in all this is to get RNTN working :P

**Comment by agibsonccc** [comment]
Right. I'm glad you guys benchmarked this. Since the GC hooks arenn't working, I'm going to make the cuda buffer keep the memory in ram and only allocate it when using it on the GPU.

It's in my interest to make multiple contexts work because I have other customers who need multiple gpu support for their clusters. So I need to make multi threaded access work in the most efficient way possible. There's going to be a lot of data sharing as well. Doing that between contexts  is a little crazy with the gpu.

**Comment by mjgp2** [comment]
Hi, I work with @Bam4d.

I think for now to proceed we'll have to manage the memory manually and disable the reaper. The system that you are replicating here seems to be how the JVM deallocates direct memory buffers using GC events - which has many issues, hence elasticsearch etc. manually deallocating buffers using reflection and prrivate JDK methods (urgh).

Using finalize also has performance impacts, although I can't quanitfy how large they are :)

**Comment by agibsonccc** [comment]
You're absolutely right and I've been benchmarking that closely. I've been weighing performance vs memory trying all the different combos to understand the trade offs. My goals are as follows:

Good abstraction for cuda where I don't have to think about it
Works in a cluster (multiple host threads)
Scales with number of gpus
Good sane data sharing (pinned memory)
Generalizable to opencl


I was exploring the limitations of what was possible with the GC but I can tell you I've seen significant performance hits with finalize. I'm a huge advocate of avoiding it.

The problem comes with the native resource (stuff being allocated).

I'm trying to overcome the limitations that you typically see with the gpu (sending data back and forth) in the best way possible.

I've ran the gamut of different solutions to see what would work and you guys verified a lot of my own private testing.

I think pinned memory allocating memory only when needed will be the only sane way to do this. 

The main thing is that the typical:
cuda alloc -> run op -> cuda get

was so slow it was useless. I had that working months ago but was useless.

I'm going to see if I can get acceptable perf with doing pinned memory and alloc when needed. The good thing is we only need to change the data buffer.

**Comment by agibsonccc** [comment]
JFYI for the community: we are almost done coming up with a solid solution for this.
