### ISSUE TITLE
dl4j examples performance: 3.8 vs. 3.9-native

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#768]
Summary of example issues and times for 3.8 vs 3.9.
Test system:
- Windows 8.1
- i7-3930k (6 core)
- OpenBLAS 0.2.14 for both 3.8 and 3.9

***Last updated: 4am, Tuesday 12th April PDT***

**Feed forward examples**

**Name** | **Time (3.8) (ms), 3 run avg** | **Time (3.9) (ms), 3 run avg** | Notes
--- | --- | --- | ----
MLPClassifierMoon | **5100** | 11178 | (time just for fit)
MLPMnistSingleLayerExample | 65628 | **27598** | *1 epoch only, fit only* (before bettertoflattened: 54891ms; as of 3 April: 41789ms)

Exact file I'm running for this: https://gist.github.com/AlexDBlack/a0ec053b86e29f67327365d47a213931

VisualVM: MLPMnistSingleLayerExample:
![image](https://cloud.githubusercontent.com/assets/2360237/14457477/14b8b218-00ee-11e6-895d-978474db2a65.png)

Of note here:
* putScalar is from the MnistDataSetIterator

---
---
---

**Convolutional Examples**

(Note: Times not yet updated post bettertoflattened, but this probably won't help much here).

**Name** | **Time (3.8) (ms)** | **Time (3.9) (ms)** | Notes
--- | --- | --- | ----
~~LenetMnistExample~~ | ~~**863291**~~ | ~~1031003~~ | ~~*1 epoch only*. nd4j-native: poor CPU utilization. Bottleneck: **tensorMmul (reshape + assign > mmul part)**; also [**this**](https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-core/src/main/java/org/deeplearning4j/nn/layers/convolution/subsampling/SubsamplingLayer.java#L101) is approx 60% of total runtime~~

**Note**: This needs to be updated to the new LenetMnistExample. Will do so once we have subsampling optimization fixed

---
---
---

**RNN Examples**

**Name** | **Time (3.8) (ms)** (avg, 2 runs) | **Time (3.9) (ms)** (avg, 2 runs) | Notes
--- | --- | --- | ----
GravesLSTMCharModellingExample | 130345 | **123306** | Bottlenecks: see below. Also note: some performance optimizations on the DL4J side (smaller number of larger ops, etc) should be possible.

Exact code I'm running: https://gist.github.com/AlexDBlack/819d9e89c9164b678e6d0cba03d89346

![image](https://cloud.githubusercontent.com/assets/2360237/14457834/c5f9f134-00f0-11e6-9f46-c63a25397acf.png)

[OLD visualvm, for reference]
![image](https://cloud.githubusercontent.com/assets/2360237/14237750/83e21640-fa6b-11e5-9d11-237bf076d35a.png)

**Comment by saudet** [comment]
When profiling `GravesLSTMCharModellingExample` on Linux, `Pointer.deallocate()` shows up only way down on the list, so it appears to be an issue with either MinGW or Windows. One way we might be able to fix this is by switching to a more efficient allocator, which we may even need on Linux at some point, such as `jemalloc`. On Linux, we can use it simply via `LD_PRELOAD` or link with it explicitly:
https://github.com/jemalloc/jemalloc/wiki/Getting-Started
but on Windows, this apparently doesn't work, and it's not obvious what can be done to try it out. Maybe these hooks from GCC would work:
https://www.gnu.org/software/libc/manual/html_node/Hooks-for-Malloc.html

**Comment by saudet** [comment]
Since we're dealing with C++, another option would be to overload the `new` and `delete` operators globally. I've quickly added a couple of macros for that to JavaCPP and they work: https://github.com/bytedeco/javacpp/commit/24abf3a5d2e54d815ef35b85ffd786023784d073
Now we could try to build jemalloc on Windows with `--with-jemalloc-prefix` and see how well that does...

**Comment by treo** [comment]
So how exactly would I have to do this to support jemalloc? Libnd4j mostly uses malloc instead of new. But since this is coming from javacpp, I guess I would have to build it with jemalloc support?

**Comment by saudet** [comment]
Well, it's a bit complicated. nd4j allocates buffers using javacpp, but libnd4j also uses malloc() independently too. The easiest might be to try the hooks for GCC, but this wouldn't work with MSVC, so I'm not feeling positive about that. BTW, CUDA supports the new and delete operators as well: http://docs.nvidia.com/cuda/cuda-samples/index.html#newdelete So we could replace all the malloc()/free() calls with new/delete first (is that OK with you @raver119 @agibsonccc?) and then experiment with jemalloc.

**Comment by treo** [comment]
I'd like to add, that the allocation / deallocation only became a problem after running training for a very long time. In the beginning I had no problem with it what so ever. Running Alex's example, I see allocate/deallocate using only about 3.6% of the time (combined). Even when creating heavy memory pressure by running the example 4 times concurrently.

To try jemalloc, I've now done the following, which I expect to do at least somewhat the correct thing. If I understand it correctly, I can use jemalloc by just linking to it at compile time. So that is what I did:

1. I installed jemalloc using pacman in msys2: ` pacman -S mingw64/mingw-w64-x86_64-jemalloc`
2. I added `-ljemalloc` to https://github.com/deeplearning4j/libnd4j/blob/master/blas/CMakeLists.txt#L27
3. I built libnd4j like usual with `bash buildnativeoperations.sh blas cpu`
5. I built nd4j with `mvn clean install -DskipTests -Dmaven.javadoc.skip=true -Djavacpp.compilerOptions=-ljemalloc -pl '!:nd4j-cuda-7.5,!:nd4j-tests'`

Now running Alex's example again, I get about 2.8% of allocate/deallocate runtime.

**Comment by saudet** [comment]
I tried using that way, but it didn't work for me. On Windows, jemalloc didn't actually link for me. Does it solve your issue with long running sessions?

**Comment by treo** [comment]
The 2.8% can be just a fluke. And as I did that just now, I didn't have the time to test a long running session yet.

**Comment by treo** [comment]
So to give everyone a little update:
Msys2 installs jemalloc with the "je_" prefix. This is what keeps us from being able to link to it simply using `-ljemalloc`. Building it from source and then linking against it works, *but* crashes the JVM on load, so this path seems to be useless on windows.

Now, I tried the path @saudet suggested, and defined an allocator and a deallocator via javacpp (see https://github.com/treo/nd4j/commit/b53687e6f9d4de7228683ab6de0a6625e2dea7db). This breaks cuda, and requires additional parameters to build (I build it using `mvn clean install -DskipTests -Dmaven.javadoc.skip=true -Djavacpp.compilerOptions='-ljemalloc,-include,c:\msys64\mingw64\include\jemalloc\jemalloc.h' -pl ':nd4j-cuda-7.5,:nd4j-tests'`), but it ends up using jemalloc for everything that is allocated through javacpp.

I haven't touched libnd4j, besides updating it to today's master, so it still uses the system allocator, where it needs to. That said, the network were I reported 40% and rising spent in allocation after 55 minutes, is now at  65 minutes, and the allocation/deallocation now use only around 3% of the time.

Now, I'll go and investigate what happens if I simply naively replace each malloc and free call on libnd4j with their jemalloc equivalents. My guess is that it will provide another nice speedup.

**Comment by raver119** [comment]
Please, beware there: cuda and cpu code still share some methods internally, including few those that are using malloc.

**Comment by treo** [comment]
I know, and I'm currently not looking to make more then a simple proof of concept, so right now I don't care about breaking cuda. I just want to see if it works at all :)

And apparently it does work (see https://github.com/treo/libnd4j/commit/56840fce21daad4a80bf7b78dda16f140510f36e). At least I'm not getting any crashes :). I'll update this comment with it's long running behavior when I'm at the 1 hour mark again.

So far, I think it would be a good idea to remove all usage of malloc/free in favor of new/delete so the the required changes could be reduced to a single file, which overrides the default new/delete operators, that way, I guess, libnd4j should still work fine with cuda.

For nd4j, I have no good idea what should be done to get it to build for both. Maybe an ifdef inside the defines? I honestly don't know, but it looks very much like it is very worthwhile to incorporate jemalloc.

**Comment by raver119** [comment]
do not change device code please!

**Comment by agibsonccc** [comment]
@raver119 @treo Raver is currently working on finishing out purging malloc from the cuda kernels and the results wouldn't matter as much. I"m not against using new/delete for everything though. I"ve seen it work in practice with cuda. I'm curious about the effects on windows though? From what I'm seeing here it won't matter much?

**Comment by treo** [comment]
The way @raver119 purges malloc is probably from the kernels is probably the best possible way: Just remove it completely by reusing the available memory. That certainly will help in the places where it is possible to do so. But I don't think that it will actually solve the problem that we see with the windows allocator and when not using cuda.

In Windows 10 it is supposed to be way better already, but as we can see, it just isn't as good as jemalloc. On Linux many of the problems that jemalloc fixes, seem to have also been fixed with new versions of glibc, but Windows users don't get these fixes, due to MinGW using the system allocator directly.

Going for new/delete everywhere in the code will probably not fix the suboptimal behavior of the Windows memory allocator (and if it does, I would be very surprised), but it opens up a simple way to support different allocators, by having an ifdef around the overriding of the new/delete operators. And even if it doesn't end up being used, it would clean up the code, just because new/delete is used in some places, malloc/free is used in others, and sometimes the usage is even mixed where a malloc-ed piece of memory is freed using delete.

My proof of concept so far was going the way of least resistance, i.e. a simple search/replace all, because I wanted to see if it actually improves the situation. I did it in full knowledge that it is horrible in every possible way, and I didn't actually expect it to work at all. But it did work, so I wanted to share it in order to support my conclusion that it is worth the work to do a proper version.

And it is very much worth it, as my RNN training went down from 4,5 epochs in ten hours (i.e. when my early stopping trainer stopped) to currently 5 epochs in 3.5 hours. Most of this improvement I attribute to using jemalloc for javacpp allocated memory. Going for it in libnd4j only resulted in an additional 10% improvement, which doesn't seem like that much, but 10% of 10 hours is still another hour.  

If needed I can try to cook up a proper version, just because I'd like to have this in as soon as possible. But as I am going away for some days, this probably will not happen before the end of next week.

**Comment by saudet** [comment]
This is what I'm getting on Fedora 23 with the latest modifications I made to LenetMnistExample:
![lenet_hotspots](https://cloud.githubusercontent.com/assets/3328023/14446086/1d145e00-008d-11e6-8c0d-bcc698ea4ca4.png)
So, it looks l'll be integrating jemalloc today...

**Comment by agibsonccc** [comment]
I just added the new/delete stuff now fwiw

**Comment by treo** [comment]
@saudet Any news on that?

**Comment by saudet** [comment]
@treo That particular issue I spotted is apparently caused by inefficient code used to subsample for CNNs here: https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-core/src/main/java/org/deeplearning4j/nn/layers/convolution/subsampling/SubsamplingLayer.java#L101
This causes over 235000 allocations per iteration in LenetMnistExample, but @AlexDBlack knows how to fix this, now that IsMax is working, right?

BTW, it doesn't change anything on Fedora 23 if we link with jemalloc explicitly, so I'm guessing recent versions of glibc do something very similar to jemalloc.

**Comment by AlexDBlack** [comment]
@saudet @treo Right, fixing that subsampling bottleneck is a WIP; was delayed a little due to some other issues with sum (now fixed afaik). I may be able to look at that again tomorrow, or the day after.
To more thoroughly test that (for correctness) I also want to add some more CNN gradient check tests.
WIP on that here: https://github.com/deeplearning4j/deeplearning4j/pull/1394

**Comment by treo** [comment]
@saudet Yes current glibc versions fare quite well in comparision with Jemalloc. Sadly that isn't available on Windows, as mingw falls back to using the system allocator. 

I've found that it is possible to force ND4J to use jemalloc from the command line by calling the build like that:
```
mvn clean install -DskipTests -Dmaven.javadoc.skip=true -pl '!:nd4j-cuda-7.5,!:nd4j-tests' -Djavacpp.compilerOptions='-DNATIVE_ALLOCATOR=je_malloc,-DNATIVE_DEALLOCATOR=je_free,-ljemalloc,-include,c:\msys64\mingw64\include\jemalloc\jemalloc.h'
```

So it is possible to support it without changing any ND4J code at all :)

Now for libnd4j I see only a hand full of malloc calls left, if those can be moved to use new/delete, then it would be possible to support jemalloc just like it is for ND4J: via a command line switch.

**Comment by saudet** [comment]
Great! Thanks for testing this

**Comment by AlexDBlack** [comment]
Closing this, as a lot of changes have occurred (to both the examples and the LSTM/CNN code) since this was last updated.
