### ISSUE TITLE
Add LAPACK to nd4j

### ISSUE THREAD

**Issue by agibsonccc** [deeplearning4j/nd4j#900]
Right nowe we don't have a native lapack backend. Add an interface and associated backend for cuda as well.

**Comment by agibsonccc** [comment]
@adamsherman any word on this? Or should we begin work on this?

**Comment by adamsherman** [comment]
I've been testing on nd4j-0.4-rc3.8 and got a few of the functions working - i.e. gelsd, so can commit - updated the Lapack interface and base classes, but was just for my own edification to get a handle on the library. Haven't been able to look at the new version in detail yet so if you guys want to have a crack first, have at it

**Comment by agibsonccc** [comment]
@adamsherman Did you ever make progress on this?

**Comment by adamsherman** [comment]
Just got it quasi working in rc3.8 - in CpuLapack/BaseLapack:

`@Override
	public void dgelsd(int m, int n, int nrhs, double[] a, int lda, double[] b, int ldb, double[] s, double rcond, int rank, double[] work,
			int lwork, int[] iwork, int info) {
LAPACK.getInstance().dgelsd(m, n, nrhs, a, lda, b, ldb, s, rcond, new intW(0), work, lwork, iwork, new intW(info));
		lwork = (int) work[0];
		work = new double[lwork];
		LAPACK.getInstance().dgelsd(m, n, nrhs, a, lda, b, ldb, s, rcond, new intW(0), work, lwork, iwork, new intW(info));}`

` /**
     * LAPACK least squares. 
     * Cleans parameters from A & B matrices for use by dgelsd lapack call.
     */
    @Override
    public void gelsd(INDArray A, INDArray B, double[] results) {
    	GelsdParams p = new GelsdParams(A,B);
    	dgelsd(A.rows(), A.columns(), B.columns(), p.getLinearA(), A.rows(), results, p.getLdb(), p.getS(), -1, p.getRank(), p.getWork(), -1, p.getIWork(), 0);
    }
`

because you need to find the optimal work length first, which the first call in CpuLapack populates. But was randomly SIGSEV'ng over multiple iterations, so I gave up and used a different solver for now. Haven't played with rc3.9 but I'd imagine could run into similar issue. The seg fault came from an arraybounds exception on the C side of things but it'd happen randomly...

**Comment by agibsonccc** [comment]
https://github.com/deeplearning4j/libnd4j/pull/214
https://github.com/deeplearning4j/nd4j/pull/971

More I have to do here yet but the interfaces are added. Need to earmark what to do with cuda.

**Comment by agibsonccc** [comment]
@saudet how is this coming?

**Comment by saudet** [comment]
PRs are in progress: #1420 and #1456
