### ISSUE TITLE
Document Additional Dependency if Dev Platform != Deployment Platform

### ISSUE THREAD

**Issue by treo** [deeplearning4j/nd4j#917]
We have already seen a case where an uberjar created on a Mac didn't work an a Linux machine.

As this case isn't going to be marginal, I think it should be well documented. And maybe even caught on ND4J load, in case that native libraries are present in the classpath but just not for the current platform.

**Comment by saudet** [comment]
I have an additional profile to include all dependencies. But as I mentioned before, users might be better served with additional "pom" artifacts that depend on the java artifacts + one or all of the classifiers. Because, I don't think the way it is now works well or at all for either Gradle or sbt anyway:
https://discuss.gradle.org/t/maven-dependencies-in-profile-section-are-not-supported/2446
http://stackoverflow.com/questions/25961765/sbt-not-resolving-transitive-dependencies-in-the-profile-section-of-pom
In the case of the presets, I don't want to have to create so many pom files for all libraries, but with nd4j we just have 2 right now, so not so bad I guess.

**Comment by saudet** [comment]
I've implemented what I'm talking about above to try out and see: 
https://github.com/deeplearning4j/nd4j/compare/sa_nativebundle 
It could be refined, but there's a couple of issues I've noticed:
1. Maven won't pick up "pom" artifacts by default when listed in dependencies: We have to specify `<type>pom</type>`.
2. At compile time, Maven needs to access to all dependencies even for "pom" artifacts, so unless artifacts for all platforms are made available somewhere, the "-all" artifacts won't install.
