### ISSUE TITLE
Dataset asList() method throws " Invalid data transform"

### ISSUE THREAD

**Issue by alirezahajibagheri** [deeplearning4j/nd4j#993]
Hi, I am trying to create a dataset with only one sample which has three features and on label . I read a data file to create such a thing using the following code:
```
        double [] labels = new double[1];
        double [] feature1 = new double[1];
        double [] feature2 = new double[1];

        int i = 0;
        Path path = Paths.get(trainPath);
        try (Scanner scanner =  new Scanner(path)){
            String[] elements = scanner.nextLine().split(",");
            feature1[i] = Double.parseDouble(elements[0]);
            feature2[i] = Double.parseDouble(elements[1]);
            labels[i] = Double.parseDouble(elements[2]);
            i++;
        }

        INDArray inputNDArray1 = Nd4j.create(feature1, new int[]{1,1});
        INDArray inputNDArray2 = Nd4j.create(feature2, new int[]{1,1});
        INDArray inputNDArray = Nd4j.hstack(inputNDArray1,inputNDArray2);

        INDArray outPut = Nd4j.create(labels, new int[]{1, 1});
        DataSet dataSet = new DataSet(inputNDArray, outPut);
        List<DataSet> listDs = dataSet.asList();
        Collections.shuffle(listDs,rng);
        return new ListDataSetIterator(listDs,batchSize);
```
As you can see I have two features and one label. This throws the following exception:

`Exception in thread "main" java.lang.IllegalStateException: Invalid data transform; features and labels do not have equal rows. First was 2 labels was 1`

Note: When I only have one feature, the above code works just fine. I am wondering if there is a bug in the code or I am doing something wrong here. Btw, I check the number of rows for both features and labels and they seem to match:

```
System.out.println(inputNDArray.size(0) + " " + inputNDArray.size(1));
System.out.println(outPut.size(0) + " " + outPut.size(1));
```

And the output is:

```
1 2
1 1
```

Thanks

**Comment by eraly** [comment]
@alirezahajibagheri You are right that when converting a dataset with only one sample to a list, only the first feature is maintained and the rest are dropped. Now, this is because of the way the asList operation works under the hood. It takes a slice of the feature array and the label array to convert to list. The assumption/expectation is more than one sample in our dataset.
You can look at more of the code here:
https://github.com/deeplearning4j/nd4j/blob/8f759523f14288d706305c108a7c988891fa2bbf/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/dataset/DataSet.java#L769

So, this is more by design. If there is a particular use in converting a single sample dataset to a list that is not covered with existing functionality that you would find useful please file an issue as a feature request. 

Thanks!
